# Generated by Django 4.0.3 on 2023-12-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_alter_product_price_alter_product_tin_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='tin_size',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
