# Generated by Django 4.0.3 on 2023-12-05 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_alter_customer_address_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='processed',
            field=models.CharField(choices=[('processed', 1), ('not processed', 0)], default='not_processed', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='processed_date',
            field=models.DateTimeField(default=None),
        ),
    ]
