# Generated by Django 4.0.3 on 2023-12-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0004_order_created_at_order_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='processed',
            field=models.IntegerField(choices=[(1, 'processed'), (0, 'not processed')], default=0, max_length=15),
        ),
    ]
